id: A23FFF7D9
title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King of
  Dharma'
type: translation
pechas:
- I80B0680A
- I03E9E322
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:11:44.341538
  last_modified_at: 2023-01-04 12:11:44.341541
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I80B0680A/5103: '4806'
  I03E9E322/678E: '4806'
